#ifndef EDITSCENE_ACTION_DEBUG_HPP
#define EDITSCENE_ACTION_DEBUG_HPP
#pragma once

#include "GoapBlackboard.hpp"
#include <Ogre.h>
#include <vector>
#include <unordered_map>

/**
 * Per-character action debug component.
 *
 * Allows test-running individual actions and inspecting the character's
 * local blackboard state. Used for debugging AI behavior in the editor.
 *
 * Path following animation states have been moved to PathFollowingComponent.
 */
struct ActionDebug {
	// Character's local GOAP blackboard
	GoapBlackboard blackboard;

	// Currently selected action for test-running
	Ogre::String selectedActionName;

	// Currently selected goal for testing
	Ogre::String selectedGoalName;

	// Test-run state
	bool isRunning = false;
	float runTimer = 0.0f;
	Ogre::String currentActionName;

	// Debug output
	Ogre::String lastResult;

	ActionDebug() = default;
};

#endif // EDITSCENE_ACTION_DEBUG_HPP
